- apps/nowait-user/package.json
- apps/nowait-user/src/App.tsx
- apps/nowait-user/src/layout/Layout.tsx
- apps/nowait-user/src/shared/Router.tsx
- router 세팅 추가 및 reactquery 설정
1. router 세팅 추가
2. 전체 layout 및 outlet 추가
3. reactQuery 설정
1. 모바일 사이즈를 어디부터 어디까지 대응 할 것인가
2. 스크롤 가능한 구조로 할 것인지, 스크롤을 막고 내부 스크롤만 가능하게 할 것인지
> feat: router, outlet 및 reactquery 설정

- apps/nowait-admin/vercel.json
정적 파일은 정적으로 응답
나버지(index.html)은 spa
> fix: vercel.json 수정

- apps/nowait-user/package.json
- apps/nowait-user/src/hooks/useInfiniteStores.ts
- apps/nowait-user/src/pages/home/HomePage.tsx
- apps/nowait-user/src/pages/home/components/InfiniteStoreList.tsx
메인 화면 모든 주점 무한 스크롤 기능 추가
현재 성능 이슈가 있어 해결 필요함.
> feat: 메인 화면 모든 주점 무한 스크롤 기능 추가

- apps/nowait-admin/src/hooks/usePostAdminLogin.tsx
- apps/nowait-admin/src/pages/AdminHome/AdminHome.tsx
- apps/nowait-admin/src/pages/LoingPage/LoginPage.tsx
로그인 기능 구현 완료
머지 후 배포한 url 통해 테스트 가능
> feat: 로그인 기능 구현 완료

- apps/nowait-admin/src/hooks/usePostAdminLogin.tsx
- apps/nowait-admin/src/pages/AdminHome/AdminHome.tsx
- apps/nowait-admin/src/pages/AdminHome/components/CardBox.tsx
- apps/nowait-admin/src/pages/AdminHome/components/WaitingCard.tsx
- apps/nowait-admin/src/pages/LoingPage/LoginPage.tsx
> fix: shadow 효과 삭제

- apps/nowait-admin/src/components/AdminSidebar.tsx
- apps/nowait-admin/src/hooks/useGetReservationList.tsx
- apps/nowait-admin/src/hooks/usePostAdminLogin.tsx
- apps/nowait-admin/src/layout/AdminLayout.tsx
- apps/nowait-admin/src/pages/AdminHome/AdminHome.tsx
- apps/nowait-admin/src/pages/AdminHome/components/CardBox.tsx
- apps/nowait-admin/src/pages/AdminHome/components/WaitingCard.tsx
- apps/nowait-admin/src/pages/LoingPage/LoginPage.tsx
> feat: 대기 목록 카드 status 필터링 구현

- apps/nowait-admin/src/components/AdminSidebar.tsx
로고 svgr로 교체 및 하단의 프로필 옆 arrow-down.svg로 교체
> feat: 사이드바 ui 약간 수정

- apps/nowait-admin/src/components/ConfirmRemoveModal.tsx
- apps/nowait-admin/src/hooks/useGetReservationList.tsx
- apps/nowait-admin/src/hooks/usePostAdminLogin.tsx
- apps/nowait-admin/src/hooks/useUpdateReservationStatus.tsx
- apps/nowait-admin/src/utils/AdminApi.tsx
> refactor: API 헤더에 토큰 추가

- apps/nowait-admin/src/pages/AdminOrders/OrderCard.tsx
> style: 메뉴 하나 주문 시 세로 중앙 정렬 되게끔 수정

- apps/nowait-admin/src/hooks/useGetReservationList.tsx
- apps/nowait-admin/src/pages/AdminHome/AdminHome.tsx
- apps/nowait-admin/src/pages/LoingPage/LoginPage.tsx
- apps/nowait-admin/src/utils/AdminApi.tsx
merge conflict 수정(adminHome) & 데이터 구조 변경으로 인한 토큰 저장 코드 변경
> fix: merge conflict 수정(adminHome) & 데이터 구조 변경으로 인한 hook 수정

- apps/nowait-admin/src/pages/LoingPage/LoginPage.tsx
> style: admin로그인 페이지 라벨링 가운데로 수정

- apps/nowait-user/src/assets/icon/cancel.svg
- apps/nowait-user/src/pages/home/HomeHeader.tsx
- apps/nowait-user/src/pages/home/HomePage.tsx
- apps/nowait-user/src/pages/home/components/MainCard.tsx
- apps/nowait-user/src/pages/home/components/MyWaitingDetail.tsx
내 입장 카드 테마 변경 및 원형 프로필 애니메이션 추가
예약 디테일 카드 넘어가는 애니메이션 추가
> feat: 메인화면 UI 최신화 완료

- apps/nowait-admin/src/pages/AdminOrders/AdminOrders.tsx
- apps/nowait-admin/src/pages/AdminOrders/OrderCard.tsx
- apps/nowait-admin/src/pages/AdminOrders/OrderPageModal.tsx
admin order 모바일 버전 구현
조리 완료 부분 detail UI 완성 시 추후 구현해야 함
> feat: admin order 모바일 버전 UI 완성

- apps/nowait-admin/src/pages/AdminBooth/components/SwipeItem.tsx
> fix: 배포 수정용

- apps/nowait-admin/src/pages/AdminBooth/components/QrGuides.tsx
> refactor: 파일 이름 수정

- apps/nowait-admin/src/components/AdminSidebar.tsx
- apps/nowait-admin/src/pages/AdminAnalytics/components/SalesCard.tsx
- apps/nowait-admin/src/pages/AdminBooth/components/Modal/menuModal.tsx
> fix: 안 쓰는 부분들 삭제(vercel 배포)

- apps/nowait-admin/src/components/AdminSidebar.tsx
- apps/nowait-admin/src/pages/AdminAnalytics/components/SalesCard.tsx
- apps/nowait-admin/src/pages/AdminBooth/components/Modal/menuModal.tsx
- apps/nowait-admin/src/pages/AdminBooth/components/QrGuides.tsx
> fix: 안쓴는 선언문 제거

- apps/nowait-admin/src/App.tsx
- apps/nowait-admin/src/pages/AdminBooth/components/AccountPage.tsx
> fix: admin라우터 기본 경로 수정 & 가이드 페이지 연결

- apps/nowait-admin/src/App.tsx
- apps/nowait-admin/src/hooks/booth/menu/useDeleteBannerImage.tsx
- apps/nowait-admin/src/hooks/booth/menu/useGetAllMenus.tsx
- apps/nowait-admin/src/pages/AdminBooth/AdminBooth.tsx
- apps/nowait-admin/src/pages/AdminBooth/components/AccountPage.tsx
- apps/nowait-admin/src/pages/AdminBooth/components/BoothSection.tsx
- apps/nowait-admin/src/pages/AdminBooth/components/MenuSection.tsx
- apps/nowait-admin/src/pages/AdminBooth/components/Modal/menuModal.tsx
> fix: 관리자용 메뉴명 추가 & 배너 삭제 api 연결

- apps/nowait-admin/src/pages/AdminOrders/OrderCard.tsx
> fix: 배포 오류 수정

- apps/nowait-admin/src/components/AdminSidebar.tsx
- apps/nowait-admin/src/pages/AdminAuth/AdminAuth.tsx
- apps/nowait-admin/src/pages/AdminBooth/components/Modal/menuModal.tsx
- apps/nowait-admin/src/pages/LoingPage/LoginPage.tsx
> fix: ui 수정

- apps/nowait-admin/src/pages/AdminOrders/AdminOrders.tsx
> refactor: admin order 헤더 부분 py값 수정

- apps/nowait-user/src/api/menu.ts
- apps/nowait-user/src/components/BackHeader.tsx
- apps/nowait-user/src/components/BackOnlyHeader.tsx
- apps/nowait-user/src/components/CommonSwiper.tsx
- apps/nowait-user/src/components/SectionDivider.tsx
- apps/nowait-user/src/components/SmallActionButton.tsx
- apps/nowait-user/src/components/common/MenuItem.tsx
- apps/nowait-user/src/components/common/MenuList.tsx
- apps/nowait-user/src/components/common/QuantitySelector.tsx
- apps/nowait-user/src/components/common/StoreListItem.tsx
- apps/nowait-user/src/components/order/ConfirmModal.tsx
- apps/nowait-user/src/components/order/PageFooterButton.tsx
- apps/nowait-user/src/pages/order/addMenu/AddMenuPage.tsx
- apps/nowait-user/src/pages/order/home/StorePage.tsx
- apps/nowait-user/src/pages/order/orderDetails/OrderDetailsPage.tsx
- apps/nowait-user/src/pages/order/orderList/OrderListPage.tsx
- apps/nowait-user/src/pages/order/remittance/RemittancePage.tsx
- apps/nowait-user/src/pages/order/remittance/components/OrderSummary.tsx
- apps/nowait-user/src/pages/order/remittance/components/RemitOptions.tsx
- apps/nowait-user/src/pages/waiting/storeDetail/StoreDetailPage.tsx
- apps/nowait-user/src/routes/Router.tsx
1. 뒤로가기 헤더 고정
2. 송금 페이지 메뉴 이미지 수정
3. 오더 리스트 애니메이션 수정
4. 송금 수단 기본값 설정
5. 폰트, 버튼, 모달 배경 색 수정
> feat: 주문 페이지 UI 수정

- packages/tailwind-config/shared-styles.css
> refactor: 공통 폰트 네이밍 및 값 수정

- apps/nowait-user/src/App.tsx
- apps/nowait-user/src/assets/icon/upIcon.svg
- apps/nowait-user/src/components/Header.tsx
- apps/nowait-user/src/components/common/toast/ErrorToast.tsx
- apps/nowait-user/src/hooks/useApiErrorHandler.ts
- apps/nowait-user/src/hooks/useCancelWaiting.ts
- apps/nowait-user/src/hooks/useInfiniteStores.ts
- apps/nowait-user/src/hooks/useMyWaitingList.ts
- apps/nowait-user/src/hooks/useWaitingStores.ts
- apps/nowait-user/src/pages/home/HomePage.tsx
- apps/nowait-user/src/pages/home/components/MyWaitingDetail.tsx
- apps/nowait-user/src/stores/toastStore.ts
에러 토스트 추가, 무한 스크롤 방식 수정, 숫자 변경 애니메이션 변경, 디테일 부분에서 상하 스크롤 막음.
> refactor: 다양한 에러 수정

- apps/nowait-user/src/components/Header.tsx
- apps/nowait-user/src/routes/Router.tsx
> refactor: 로그아웃 기능 구현

- apps/nowait-user/src/hooks/useInfiniteStores.ts
- apps/nowait-user/src/pages/home/HomePage.tsx
- apps/nowait-user/src/pages/home/components/InfiniteStoreList.tsx
- apps/nowait-user/src/pages/home/components/SortWaitingCard.tsx
- 대기 카드 가로 스크롤 시 mx-[-20px]가 되도록 수정
- 메인 화면에서 다른 화면으로 이동 후 메인 화면으로 돌아올 시 정상적으로 주점이 렌더링 되지 않는 문제 해결
> refactor: 대기 카드 ui 수정, 무한 스크롤 버그 수정

- apps/nowait-admin/src/App.tsx
- apps/nowait-admin/src/pages/AdminOrders/AdminOrders.tsx
- apps/nowait-admin/src/pages/AdminOrders/CookedPage.tsx
- apps/nowait-admin/src/pages/AdminOrders/DetailCard.tsx
- apps/nowait-admin/src/pages/AdminOrders/OrderCard.tsx
- apps/nowait-admin/src/pages/AdminOrders/OrderPageModal.tsx
> refactor: admin order부분 오류 사항 해결

- apps/nowait-user/src/components/Header.tsx
- apps/nowait-user/src/components/common/modal/SearchModal.tsx
- apps/nowait-user/src/pages/home/HomePage.tsx
- apps/nowait-user/src/pages/home/components/CancelWaitingModal.tsx
- apps/nowait-user/src/pages/home/components/HomeIcon.tsx
- apps/nowait-user/src/pages/home/components/InfiniteStoreList.tsx
- apps/nowait-user/src/pages/home/components/MainCard.tsx
- apps/nowait-user/src/pages/home/components/MyWaitingDetail.tsx
- packages/tailwind-config/shared-styles.css
- 검색 부분 스크롤 안되던 문제 해결
- 검색 글씨 변경 text-black-90
- 전체적인 폰트 반영
- 메뉴 애니메이션 효과 수정
> refactor: user 검색 부분 수정 사항 반영 및 전체적인 폰트 수정

- apps/nowait-admin/src/pages/AdminBooth/components/Modal/menuModal.tsx
- packages/tailwind-config/shared-styles.css
> fix: 폰트 수정 및 추가

- apps/nowait-admin/src/pages/AdminBooth/components/Modal/menuModal.tsx
> fork 자동화 테스트

- apps/nowait-admin/src/components/AdminSidebar.tsx
- apps/nowait-admin/src/components/MenuItem.tsx
> fix: 폰트 수정

- apps/nowait-user/src/components/Header.tsx
- apps/nowait-user/src/components/icons/MemoizedIcons.tsx
- apps/nowait-user/src/pages/home/HomePage.tsx
- apps/nowait-user/src/pages/home/components/MyWaitingCard.tsx
> refactor: 새로고침 시 메인 화면의 svg 재렌더 되는 문제 해결

- apps/nowait-admin/src/pages/AdminBooth/components/AccountPage.tsx
> fix: 입금계좌 설정 페이지 에러 메세지 & 초기화 로직 수정

- apps/nowait-admin/src/pages/AdminOrders/AdminOrders.tsx
> fix: 주문페이지 새로고침 버튼 애니메이션 적용

- apps/nowait-user/src/hooks/useInfiniteStores.ts
- apps/nowait-user/src/pages/home/components/InfiniteStoreList.tsx
> feat: 일부 안드로이드 기기 및 크롬에서 무한 스크롤이 되지 않는 문제 해결

- apps/nowait-user/src/api/order.ts
- apps/nowait-user/src/components/LoadingSpinner.tsx
- apps/nowait-user/src/components/common/MenuList.tsx
- apps/nowait-user/src/hooks/useWaitingStores.ts
- apps/nowait-user/src/pages/order/remittance/RemittancePage.tsx
> fix: 타입 에러 수정

- apps/nowait-admin/src/pages/AdminBooth/components/MenuSection.tsx
> fix: 배포에러수정

- apps/nowait-admin/src/pages/AdminBooth/components/AccountPage.tsx
> fix: 입금 계좌 관리 설정 에러 수정

- apps/nowait-user/src/pages/waiting/storeDetail/StoreDetailPage.tsx
- apps/nowait-user/src/pages/waiting/waitingPartysize/WaitingPartySizeForm.tsx
예약 인원 설정 페이지 css 수정
주점 페이지 로딩 스피너 추가
> feat: 예약 인원 설정 페이지 css 수정 및 주점 페이지 로딩 스피너 추가

- apps/nowait-admin/src/pages/AdminBooth/components/AccountPage.tsx
> fix: 입급 계좌 설정 버튼 색깔 수정

- apps/nowait-admin/src/components/ConfirmRemoveModal.tsx
> fix:로그아웃 모달창 ui 수정

- apps/nowait-user/src/pages/login/LoginPage.tsx
> refactor: 전체 화면 수치 수정

- apps/nowait-user/src/components/AuthGuard.tsx
> refactor: accessToken이 이미 있는 상태에서 로그인을 하면 root로 강제 이동 로직 추가

- apps/nowait-admin/src/pages/AdminBooth/components/AccountPage.tsx
- apps/nowait-admin/src/pages/AdminHome/AdminHome.tsx
> fix: ibk 기업 --> 전송시 띄어쓰기 삭제

- apps/nowait-admin/src/pages/AdminHome/components/RoundTabButton.tsx
> fix: 라운드 탭 버튼 옆 카드 개수 추가

- apps/nowait-admin/src/pages/AdminOrders/AdminOrders.tsx
- apps/nowait-user/src/pages/home/components/MyWaitingSection.tsx
- apps/nowait-user/src/pages/home/components/SortWaitingCard.tsx
- apps/nowait-user/src/pages/home/components/WaitingListModal.tsx
> refactor: 현재 시간에 9시간 추가

- apps/nowait-user/src/components/common/modal/SearchModal.tsx
> refactor: 헤더 수정

- apps/nowait-user/vercel.json
> refactor: vercel.json 설정 수정

- apps/nowait-user/src/components/SmallActionButton.tsx
- apps/nowait-user/src/pages/order/orderList/components/CartItem.tsx
- apps/nowait-user/src/pages/waiting/storeNotice/StoreNoticePage.tsx
1. 공지사항 태그 변환
2. 폰트 및 스몰 버튼 bg 변경
> feat: 웨이팅 페이지 변경사항 적용

- apps/nowait-user/src/api/order.ts
- apps/nowait-user/vercel.json
> Merge to main

- apps/nowait-user/src/api/order.ts
- apps/nowait-user/vercel.json
> fix: order api 수정

- apps/nowait-user/src/pages/home/components/CancelWaitingModal.tsx
- apps/nowait-user/src/pages/login/LoginPage.tsx
> refactor: 모달 크기 수정

- apps/nowait-user/src/api/menu.ts
- apps/nowait-user/src/api/order.ts
- apps/nowait-user/src/api/reservation.ts
- apps/nowait-user/src/pages/order/addMenu/AddMenuPage.tsx
- apps/nowait-user/src/pages/order/home/StorePage.tsx
- apps/nowait-user/src/pages/order/orderDetails/OrderDetailsPage.tsx
- apps/nowait-user/src/pages/order/orderList/OrderListPage.tsx
- apps/nowait-user/src/pages/order/remittance/RemittancePage.tsx
- apps/nowait-user/src/pages/order/remittenceWait/RemittanceWaitPage.tsx
- apps/nowait-user/src/pages/waiting/WaitingSummary/WaitingSummaryPage.tsx
- apps/nowait-user/src/pages/waiting/storeDetail/StoreDetailPage.tsx
- apps/nowait-user/src/types/order/order.ts
- apps/nowait-user/vercel.json
> feat: 주점 publicCode 추가

- apps/nowait-admin/src/pages/AdminAnalytics/components/BoothSalesRankingCard .tsx
- apps/nowait-admin/src/pages/AdminAnalytics/components/HeaderStatus.tsx
- apps/nowait-admin/src/pages/AdminHome/AdminHome.tsx
- apps/nowait-admin/src/pages/AdminOrders/AdminOrders.tsx
> fix: 데스크톱 화면 --> 관리자 ui 모두 여백 30px 제외 화면 꽉 채우게 구현

- apps/nowait-admin/src/pages/AdminOrders/AdminOrders.tsx
- apps/nowait-user/src/api/reservation.ts
- apps/nowait-user/src/pages/order/home/StorePage.tsx
- apps/nowait-user/src/pages/waiting/storeDetail/StoreDetailPage.tsx
- apps/nowait-user/src/types/wait/store.ts
주점 detailpage 불러올 때 publicCode도 받아올 수 있도록 수정
> refactor: 메뉴 정상 출력 되도록 api 수정

- apps/nowait-user/src/pages/order/home/StorePage.tsx
> refactor: 주문 조회 api 경로 수정

- apps/nowait-user/src/pages/waiting/WaitingSummary/WaitingSummaryPage.tsx
> fix: storeId 에서 publicCode로 변경

- apps/nowait-admin/src/pages/AdminBooth/AdminBooth.tsx
- apps/nowait-admin/src/pages/AdminBooth/components/AccountPage.tsx
- apps/nowait-admin/src/pages/AdminBooth/components/BoothSection.tsx
- apps/nowait-admin/src/pages/AdminBooth/components/MenuSection.tsx
- apps/nowait-admin/src/pages/AdminBooth/components/NoticeEditor.tsx
- apps/nowait-admin/src/pages/AdminBooth/components/OperatingTimeSelector.tsx
> fix: 부스 관리 페이지 반응형 롤백 & 배너이미지 반응형 반영

- apps/nowait-admin/src/pages/AdminBooth/components/AccountPage.tsx
> fix: 배너이미지 반응형(모바일)

- apps/nowait-admin/src/components/NewOrderToast.tsx
- apps/nowait-admin/src/components/closeButton.tsx
- apps/nowait-admin/src/global.css
- apps/nowait-admin/src/layout/AdminLayout.tsx
> fix: 토스트 알림 디자인 & 삭제 구현

- apps/nowait-admin/src/components/NewOrderToast.tsx
- apps/nowait-admin/src/pages/AdminBooth/components/AccountPage.tsx
- apps/nowait-admin/src/pages/AdminBooth/components/MenuSection.tsx
- apps/nowait-admin/src/pages/AdminBooth/components/Swipe/SwipeableRow.tsx
> fix: 스와이프 메뉴 삭제 로직 구현 & 애니메이션 효과는 미완성

- apps/nowait-user/.gitignore
- apps/nowait-user/vite.config.ts
> feat: 환경변수 및 경로 수정

- apps/nowait-admin/src/components/NewOrderToast.tsx
- apps/nowait-admin/src/hooks/useDetectNewOrders.tsx
- apps/nowait-admin/src/hooks/useNewOrderToastStore.tsx
- apps/nowait-admin/src/pages/AdminOrders/AdminOrders.tsx
> fix: 토스트 알림 로직 --> qa 피드백 적용

- apps/nowait-admin/src/hooks/useNewOrderToastStore.tsx
- apps/nowait-admin/src/pages/AdminOrders/AdminOrders.tsx
> fix: 토스트 알림 --> 주문상세 입금확인 클릭시 해당 알림 자동 삭제

- apps/nowait-user/src/utils/initSentry.ts
> feat: log monitoring 추가

- apps/nowait-admin/src/pages/AdminOrders/AdminOrders.tsx
- apps/nowait-admin/src/pages/AdminOrders/DetailCard.tsx
- apps/nowait-admin/src/pages/AdminOrders/OrderCard.tsx
> refactor: 조리중 화면에서도 디테일 화면 표시 추가

- apps/nowait-admin/src/pages/AdminOrders/DetailCard.tsx
> refactor: 에러 수정

- apps/nowait-user/src/utils/initSentry.ts
> refactor: sentry 로컬 환경 제거

- apps/nowait-admin/src/pages/AdminBooth/components/MenuSection.tsx
> fix: 메뉴 순서 편집시 발생하는 드래그 에러 수정

- apps/nowait-admin/src/components/NewOrderToast.tsx
- apps/nowait-admin/src/pages/AdminBooth/components/MenuSection.tsx
> fix: 토스트 알림 클릭시  상세주문정보 오픈 & 토스트 알림제거

- apps/nowait-user/src/pages/login/components/PhoneNumberInput.tsx
> refactor: 아이폰에서 input 박스 바깥으로 x버튼이 빠져 나가는 문제 수정

- apps/nowait-admin/src/types/order.ts
> refactor: type 수정

- apps/nowait-admin/src/hooks/analytics/useGetPopularMenu.tsx
- apps/nowait-admin/src/pages/AdminAnalytics/AdminAnalytics.tsx
- apps/nowait-admin/src/pages/AdminAnalytics/components/HeaderStatus.tsx
> fix: 통계페이지 모바일 반응형 수정

- apps/nowait-admin/src/components/NewOrderToast.tsx
- apps/nowait-admin/src/global.css
- apps/nowait-admin/src/pages/AdminHome/components/WaitingCard.tsx
> fix: 웨이팅 카드 폰트 충돌 해결

- apps/nowait-user/src/api/order.ts
- apps/nowait-user/src/utils/accountFormat.ts
> feat: 오더 페이지 수정

- apps/nowait-user/src/api/order.ts
> feat: 주문 api 수정

- apps/nowait-admin/src/pages/AdminHome/AdminHome.tsx
- apps/nowait-admin/src/pages/AdminHome/components/WaitingCard.tsx
> fix: 웨이팅 카드 폰넘버 적용

- apps/nowait-admin/src/pages/AdminHome/AdminHome.tsx
> fix: 타입 수정

- apps/nowait-user/src/pages/login/components/TermsModal.tsx
- apps/nowait-user/src/pages/login/onboarding/OnboardingPage.tsx
- apps/nowait-user/src/pages/login/onboarding/OnboardingSuccessPage.tsx
- apps/nowait-user/src/utils/UserApi.tsx
> feat: 로그인 전화번호 받는 로직 추가

- apps/nowait-user/src/utils/UserApi.tsx
> feat: api 경로 수정

- apps/nowait-user/src/pages/login/components/TermsModal.tsx
> feat: 하이픈 제거

- apps/nowait-admin/src/pages/AdminBooth/AdminBooth.tsx
- apps/nowait-admin/src/pages/AdminBooth/components/BoothSection.tsx
- apps/nowait-admin/src/utils/cropUserSelect.tsx
> fix: 이미지 품질 저하 개선(crop시 2배수로)

- apps/nowait-admin/src/pages/AdminBooth/components/BoothSection.tsx
- apps/nowait-admin/src/pages/AdminBooth/components/Modal/PreviewModal.tsx
> fix: 미리보기 모달 깨짐현상 수정

- apps/nowait-admin/src/pages/AdminAnalytics/components/HeaderStatus.tsx
- apps/nowait-admin/src/pages/AdminBooth/components/BoothSection.tsx
> fix: 통계 모바일 화면 & 배너이미지 가로 스크롤 허용

- apps/nowait-user/src/components/layout/CenteredContentLayout.tsx
- apps/nowait-user/src/components/order/PageFooterButton.tsx
> feat: 오더 페이지 css 수정

- apps/nowait-user/src/components/BackHeader.tsx
> feat: 헤더 zIndex 수정

- apps/nowait-admin/src/hooks/useRemoveEmoji.tsx
> feat: 정규식 모음추가

- apps/nowait-admin/src/pages/AdminBooth/components/Modal/menuModal.tsx
> feat: IME조합 추가
